package aws

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/anadinema/yak/internal/config"
	"github.com/anadinema/yak/internal/resolver"
	"github.com/anadinema/yak/internal/state"
)

type ResolvedAccount struct {
	Name      string
	AccountID string
	RoleName  string
	RoleARN   string
	Region    string
	SSOStart  string
	SSORegion string
}

func ResolveAccount(
	cfg *config.Config,
	account *config.Account,
	roleTier string,
	res *resolver.Resolver,
) (*ResolvedAccount, error) {

	accountId, err := res.Resolve(account.AccountID)
	if err != nil {
		return nil, fmt.Errorf("account %q account_id: %w", account.Name, err)
	}

	rawRoleName := cfg.Roles[roleTier]
	if override, ok := account.RoleOverrides[roleTier]; ok {
		rawRoleName = override
	}
	roleName, err := res.Resolve(rawRoleName)
	if err != nil {
		return nil, fmt.Errorf("account %q role %q: %w", account.Name, roleTier, err)
	}

	// Resolve SSO start URL
	ssoStart, err := res.Resolve(cfg.AWS.SSOStartURL)
	if err != nil {
		return nil, fmt.Errorf("sso_start_url: %w", err)
	}

	region := config.EffectiveRegion(cfg, account)

	return &ResolvedAccount{
		Name:      account.Name,
		AccountID: accountId,
		RoleName:  roleName,
		RoleARN:   fmt.Sprintf("arn:aws:iam::%s:role/%s", accountId, roleName),
		Region:    region,
		SSOStart:  ssoStart,
		SSORegion: region,
	}, nil
}

func WriteConfig(configPath, ssoSessionName string, accounts []ResolvedAccount) error {
	rendered, err := RenderConfig(ssoSessionName, accounts)
	if err != nil {
		return err
	}
	_, err = WriteConfigIfChanged(configPath, rendered)
	if err != nil {
		return err
	}

	configState := &state.AWSConfigState{
		UpdatedAt: time.Now().UTC(),
		Profiles:  make(map[string]state.ProfileAWSConfigState, len(accounts)),
	}
	for _, account := range accounts {
		configState.Profiles[account.Name] = state.ProfileAWSConfigState{
			AccountID: account.AccountID,
			RoleName:  account.RoleName,
			Region:    account.Region,
		}
	}

	return state.SaveAWSConfigState(configState)
}

// RenderConfig returns full AWS config text for the resolved accounts.
func RenderConfig(ssoSessionName string, accounts []ResolvedAccount) (string, error) {
	if len(accounts) == 0 {
		return "", fmt.Errorf("no accounts to write")
	}

	var sb strings.Builder
	sb.WriteString("# Generated by yak — do not edit manually\n")
	sb.WriteString("# Run 'yak setup' to regenerate\n\n")

	// Write the single shared sso-session block
	_, _ = fmt.Fprintf(&sb, "[sso-session %s]\n", ssoSessionName)
	_, _ = fmt.Fprintf(&sb, "sso_start_url            = %s\n", accounts[0].SSOStart)
	_, _ = fmt.Fprintf(&sb, "sso_region               = %s\n", accounts[0].SSORegion)
	_, _ = fmt.Fprintf(&sb, "sso_registration_scopes  = sso:account:access\n")
	sb.WriteString("\n")

	// Write one profile block per account
	for _, a := range accounts {
		_, _ = fmt.Fprintf(&sb, "[profile %s]\n", a.Name)
		_, _ = fmt.Fprintf(&sb, "sso_session    = %s\n", ssoSessionName)
		_, _ = fmt.Fprintf(&sb, "sso_account_id = %s\n", a.AccountID)
		_, _ = fmt.Fprintf(&sb, "sso_role_name  = %s\n", a.RoleName)
		_, _ = fmt.Fprintf(&sb, "region         = %s\n", a.Region)
		sb.WriteString("\n")
	}
	return sb.String(), nil
}

// ConfigChanged reports whether rendered differs from existing AWS config on disk.
func ConfigChanged(configPath, rendered string) (bool, error) {
	configPath = expandHome(configPath)
	existing, err := os.ReadFile(configPath)
	if err != nil {
		if os.IsNotExist(err) {
			return true, nil
		}
		return false, fmt.Errorf("could not read AWS config %q: %w", configPath, err)
	}
	return string(existing) != rendered, nil
}

// WriteConfigIfChanged writes rendered AWS config only when content differs.
// Returns true when file was written, false when content was unchanged.
func WriteConfigIfChanged(configPath, rendered string) (bool, error) {
	configPath = expandHome(configPath)
	if err := os.MkdirAll(filepath.Dir(configPath), 0700); err != nil {
		return false, fmt.Errorf("could not create AWS config directory: %w", err)
	}

	changed, err := ConfigChanged(configPath, rendered)
	if err != nil {
		return false, err
	}
	if !changed {
		return false, nil
	}

	if err := os.WriteFile(configPath, []byte(rendered), 0600); err != nil {
		return false, fmt.Errorf("could not write AWS config %q: %w", configPath, err)
	}
	return true, nil
}

func ExportCredentials(credentialsPath, profileName string) error {
	credentialsPath = expandHome(credentialsPath)
	if err := os.MkdirAll(filepath.Dir(credentialsPath), 0700); err != nil {
		return fmt.Errorf("could not create credentials directory: %w", err)
	}

	out, err := exec.Command(
		"aws", "configure", "export-credentials",
		"--profile", profileName,
		"--format", "env-no-export",
	).Output()
	if err != nil {
		return fmt.Errorf("aws configure export-credentials failed for profile %q: %w", profileName, err)
	}

	creds := parseEnvCredentials(string(out), profileName)

	// TODO: Revisit this. Not sure if this is needed.
	existing := readCredentials(credentialsPath)
	existing[profileName] = creds

	return writeCredentials(credentialsPath, existing)
}

func ExportAllCredentials(credentialsPath string, profiles []string) error {
	for _, p := range profiles {
		if err := ExportCredentials(credentialsPath, p); err != nil {
			return fmt.Errorf("exporting credentials for %q: %w", p, err)
		}
	}
	return nil
}

func SsoLoginForProfile(profileName string) error {
	cmd := exec.Command("aws", "sso", "login", "--profile", profileName)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func CheckSafeguard(
	cfg *config.Config,
	account *config.Account,
	requestedRole string,
) error {
	if !cfg.Safeguards.Enabled || (account.Safeguard != nil && !*account.Safeguard) || !isProtected(cfg, account.Name) {
		return nil
	}

	powerCeiling := cfg.Safeguards.MaxPowerGradeAllowed
	if config.PowerGrade(requestedRole) > config.PowerGrade(powerCeiling) {
		return fmt.Errorf(
			"safeguard: role %q (power grade %d) exceeds the maximum allowed role %q (power grade %d) on protected account %q.\n"+
				"Use --bypass-safeguards to override (requires confirmation)",
			requestedRole, config.PowerGrade(requestedRole),
			powerCeiling, config.PowerGrade(powerCeiling),
			account.Name,
		)
	}
	return nil
}

func isProtected(cfg *config.Config, name string) bool {
	for _, p := range cfg.Safeguards.ProtectedAccounts {
		if p == name {
			return true
		}
	}
	if cfg.Safeguards.ProtectedPattern != "" {
		re, err := regexp.Compile(cfg.Safeguards.ProtectedPattern)
		if err == nil && re.MatchString(name) {
			return true
		}
	}
	return false
}

func IsRoleAllowed(account *config.Account, role string) bool {
	if len(account.AllowedRoles) == 0 {
		return true
	}
	for _, r := range account.AllowedRoles {
		if r == role {
			return true
		}
	}
	return false
}

// ── helpers ───────────────────────────────────────────────────────────────────

func expandHome(path string) string {
	if strings.HasPrefix(path, "~/") {
		home, _ := os.UserHomeDir()
		return filepath.Join(home, path[2:])
	}
	return path
}

func parseEnvCredentials(raw, profile string) map[string]string {
	result := make(map[string]string)
	for _, line := range strings.Split(raw, "\n") {
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		switch strings.TrimSpace(parts[0]) {
		case "AWS_ACCESS_KEY_ID":
			result["aws_access_key_id"] = strings.TrimSpace(parts[1])
		case "AWS_SECRET_ACCESS_KEY":
			result["aws_secret_access_key"] = strings.TrimSpace(parts[1])
		case "AWS_SESSION_TOKEN":
			result["aws_session_token"] = strings.TrimSpace(parts[1])
		}
	}
	return result
}

// readCredentials reads an ini-style credentials file into a nested map.
func readCredentials(path string) map[string]map[string]string {
	result := make(map[string]map[string]string)
	data, err := os.ReadFile(path)
	if err != nil {
		return result
	}
	var current string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			current = line[1 : len(line)-1]
			result[current] = make(map[string]string)
		} else if current != "" && strings.Contains(line, "=") {
			parts := strings.SplitN(line, "=", 2)
			result[current][strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
		}
	}
	return result
}

// writeCredentials writes the credential map to an ini-style file.
func writeCredentials(path string, creds map[string]map[string]string) error {
	var sb strings.Builder
	sb.WriteString("# Generated by yak — do not edit manually\n\n")
	for profile, vals := range creds {
		_, _ = fmt.Fprintf(&sb, "[%s]\n", profile)
		for k, v := range vals {
			_, _ = fmt.Fprintf(&sb, "%s = %s\n", k, v)
		}
		sb.WriteString("\n")
	}
	return os.WriteFile(path, []byte(sb.String()), 0600)
}
